-- Generated by tools/gen_vendor.py; do not edit.
-- Items: LibPeriodicTable-3.1 Tradeskill.Mat.BySource.Vendor @ 130c6a9f7367 (LGPL-2.1).
-- Prices: wago.tools ItemSparse BuyPrice / VendorStackCount, wow_classic_beta 1.60.1.70009, 2026-09-25.
---@type string, table
local _, ns = ...

-- [itemID] = copper per unit
ns.VendorPrices = {
	[159] = 5, -- Refreshing Spring Water
	[1179] = 25, -- Ice Cold Milk
	[2320] = 10, -- Coarse Thread
	[2321] = 100, -- Fine Thread
	[2324] = 25, -- Bleach
	[2325] = 1000, -- Black Dye
	[2596] = 120, -- Skin of Dwarven Stout
	[2604] = 50, -- Red Dye
	[2605] = 100, -- Green Dye
	[2678] = 2, -- Mild Spices
	[2692] = 40, -- Hot Spices
	[2880] = 100, -- Weak Flux
	[2894] = 50, -- Rhapsody Malt
	[2928] = 20, -- Dust of Decay
	[2930] = 50, -- Essence of Pain
	[3371] = 4, -- Empty Vial
	[3372] = 40, -- Leaded Vial
	[3466] = 2000, -- Strong Flux
	[3713] = 160, -- Soothing Spices
	[3857] = 500, -- Coal
	[4289] = 50, -- Salt
	[4291] = 500, -- Silken Thread
	[4340] = 350, -- Gray Dye
	[4341] = 500, -- Yellow Dye
	[4342] = 2500, -- Purple Dye
	[4400] = 2000, -- Heavy Stock
	[4470] = 38, -- Simple Wood
	[4536] = 5, -- Shiny Red Apple
	[5173] = 100, -- Deathweed
	[6260] = 50, -- Blue Dye
	[6261] = 1000, -- Orange Dye
	[6530] = 100, -- Nightcrawlers
	[8150] = 1000, -- Deeprock Salt
	[8343] = 2000, -- Heavy Silken Thread
	[8923] = 200, -- Essence of Agony
	[8924] = 100, -- Dust of Deterioration
	[8925] = 500, -- Crystal Vial
	[10290] = 2500, -- Pink Dye
	[10647] = 2000, -- Engineer's Ink
	[10648] = 500, -- Blank Parchment
	[11291] = 4500, -- Star Wood
	[14341] = 5000, -- Rune Thread
	[15409] = 4000, -- Refined Deeprock Salt
	[17020] = 1000, -- Arcane Powder
	[17034] = 200, -- Maple Seed
	[17035] = 400, -- Stranglethorn Seed
	[17194] = 2, -- Holiday Spices
	[17196] = 50, -- Holiday Spirits
	[18256] = 6000, -- Imbued Vial
	[18567] = 150000, -- Elemental Flux
}
