-- Builds tests/forever_api.lua: every function and event the WoW: Forever client documents.
-- Source: Gethe/wow-ui-source, branch "forever", Interface/AddOns/Blizzard_APIDocumentationGenerated.
-- Usage: lua5.1 tools/gen_api_index.lua <wow-ui-source checkout> > tests/forever_api.lua
local root = assert(arg[1], "path to a wow-ui-source checkout (branch forever)")
local dir = root .. "/Interface/AddOns/Blizzard_APIDocumentationGenerated/"
local functions, events, secret, restricted = {}, {}, {}, {}
APIDocumentation = { AddDocumentationTable = function(_, t)
	local prefix = t.Namespace and (t.Namespace .. ".") or ""
	for _, f in ipairs(t.Functions or {}) do
		functions[prefix .. f.Name] = true
		if f.HasRestrictions then
			restricted[prefix .. f.Name] = true
		end
		if f.SecretArguments or f.SecretReturns or f.SecretWhen then
			secret[prefix .. f.Name] = tostring(f.SecretArguments or f.SecretReturns or f.SecretWhen)
		end
	end
	for _, e in ipairs(t.Events or {}) do
		events[e.LiteralName] = true
	end
end }
local version = io.open(root .. "/version.txt"):read("*l")
for file in io.popen('ls "' .. dir .. '"'):lines() do
	if file:match("%.lua$") then
		local chunk = assert(loadfile(dir .. file))
		-- Docs reference Enum.X.Y / Constants.X at load time; any unknown global is a bottomless dummy.
		local dummy
		dummy = setmetatable({}, { __index = function() return dummy end, __call = function() return dummy end,
			__add = function() return 0 end, __sub = function() return 0 end, __unm = function() return 0 end,
			__mul = function() return 0 end, __div = function() return 0 end, __mod = function() return 0 end,
			__pow = function() return 0 end, __concat = function() return "" end })
		setfenv(chunk, setmetatable({ APIDocumentation = APIDocumentation }, { __index = function(_, k)
			return _G[k] ~= nil and _G[k] or dummy
		end }))
		chunk()
	end
end
local function sorted(t)
	local list = {}
	for k in pairs(t) do list[#list + 1] = k end
	table.sort(list)
	return list
end
print("-- Generated by tools/gen_api_index.lua from Gethe/wow-ui-source (forever) " .. version .. ". Do not edit.")
print("return {")
print('\tversion = "' .. version .. '",')
print("\tfunctions = {")
for _, k in ipairs(sorted(functions)) do print(('\t\t["%s"] = true,'):format(k)) end
print("\t},")
print("\trestricted = {")
for _, k in ipairs(sorted(restricted)) do print(('\t\t["%s"] = true,'):format(k)) end
print("\t},")
print("\tevents = {")
for _, k in ipairs(sorted(events)) do print(('\t\t["%s"] = true,'):format(k)) end
print("\t},")
print("}")
