#!/usr/bin/env python3
"""Make the CraftWise_Music addon from your own songs (issue #17).

WoW can't start a sound in the middle, so each song is cut into short .ogg chunks that
CraftWise plays one after another; "resume" continues from the chunk where it stopped.

Usage:
    python3 tools/music_split.py "<WoW>/_classic_beta_/Interface/AddOns" CraftWise_Music/Songs/*.mp3 [--chunk 2]

A split song keeps the file name, so it replaces the same song added by name in game.

Creates (or adds to) <AddOns>/CraftWise_Music/:
    CraftWise_Music.toc, Songs.lua, <song name>/001.ogg, 002.ogg, ...
Needs ffmpeg. Restart the game afterwards (new files are not seen after /reload).
Songs are yours: keep this folder out of anything you publish.
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ADDON = "CraftWise_Music"
INTERFACE = "16001"


def folder_name(path: Path) -> str:
    """A safe folder name for the chunks (ASCII letters, digits, underscores)."""
    name = re.sub(r"\(.*?\)|\[.*?\]", "", path.stem)
    name = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
    return name or "song"


def lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'



def split(src: Path, dest: Path, chunk: float) -> int:
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    subprocess.run(
        [
            "ffmpeg", "-loglevel", "error", "-y", "-i", str(src), "-vn",
            "-ac", "2", "-ar", "44100", "-c:a", "libvorbis", "-q:a", "5",
            "-f", "segment", "-segment_time", str(chunk), "-segment_start_number", "1",
            "-reset_timestamps", "1", str(dest / "%03d.ogg"),
        ],
        check=True,
    )
    files = sorted(dest.glob("*.ogg"))
    last = chunk
    if files and shutil.which("ffprobe"):
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(files[-1])],
            capture_output=True, text=True,
        ).stdout.strip()
        last = round(float(out), 2) if out else chunk
    # The song keeps the file's own name (without extension), as when it is added in game, so a
    # split song replaces the whole-file entry and existing profession choices keep working.
    (dest / "meta.json").write_text(json.dumps({"length": chunk, "last": last, "source": src.name, "name": src.stem}))
    return len(files)


def write_addon(root: Path) -> list:
    songs = []
    for d in sorted(p for p in root.iterdir() if p.is_dir()):
        meta = d / "meta.json"
        chunks = len(list(d.glob("*.ogg")))
        if not meta.exists() or chunks == 0:
            continue
        info = json.loads(meta.read_text())
        songs.append((info.get("name", d.name), d.name, chunks, info["length"], info.get("last", info["length"])))
    lines = [
        "-- Generated by CraftWise tools/music_split.py. Your own songs; not part of CraftWise.",
        "CraftWiseMusicSongs = {",
    ]
    for name, folder, chunks, length, last in songs:
        path = f"Interface\\\\AddOns\\\\{ADDON}\\\\{folder}\\\\"
        lines.append(f'\t[{lua_string(name)}] = {{ path = "{path}", chunks = {chunks}, length = {length}, last = {last} }},')
    lines.append("}")
    (root / "Songs.lua").write_text("\n".join(lines) + "\n")
    (root / f"{ADDON}.toc").write_text(
        f"## Interface: {INTERFACE}\n## Title: CraftWise Music\n"
        "## Notes: Your songs for CraftWise's Music tab\n\nSongs.lua\n"
    )
    return songs


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("addons", type=Path, help="the Interface/AddOns folder")
    ap.add_argument("songs", type=Path, nargs="*", help="mp3/ogg/wav/m4a files to add")
    ap.add_argument("--chunk", type=float, default=2.0, help="chunk length in seconds (default 2)")
    args = ap.parse_args()
    if not shutil.which("ffmpeg") and args.songs:
        print("ffmpeg not found (macOS: brew install ffmpeg)", file=sys.stderr)
        return 1
    root = args.addons / ADDON
    root.mkdir(parents=True, exist_ok=True)
    for src in args.songs:
        n = split(src, root / folder_name(src), args.chunk)
        print(f"{src.name}: {n} chunks of {args.chunk:g}s")
    for name, _, chunks, length, _ in write_addon(root):
        print(f"  {name}: {chunks} x {length:g}s")
    print("Restart the game to load new songs.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
