#!/usr/bin/env python3
"""Turn videos into flipbook frames for CraftWise's video window (issue #19).

WoW addons can't play video files, so each video is cut into small frames at a low frame
rate, packed on 1024x1024 TGA sprite sheets that CraftWise flips through. No sound: pick
the song separately in the Music tab.

Usage:
    python3 tools/video_frames.py "<WoW>/_classic_beta_/Interface/AddOns" CraftWise_Music/Videos/clip.mp4
        [--size 192] [--fps 10] [--max-seconds 30]

Writes <AddOns>/CraftWise_Music/Videos/<name>/001.tga ... and CraftWise_Music/Videos.lua.
Needs ffmpeg. Restart the game afterwards.
"""
import argparse
import json
import math
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ADDON = "CraftWise_Music"
INTERFACE = "16001"
SHEET = 1024


def folder_name(path: Path) -> str:
    name = re.sub(r"\(.*?\)|\[.*?\]", "", path.stem)
    name = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
    return name or "video"


def lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def probe_size(src: Path):
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height",
         "-of", "csv=p=0", str(src)],
        capture_output=True, text=True, check=True,
    ).stdout.strip().split(",")
    return int(out[0]), int(out[1])


def cell_size(width: int, height: int, size: int):
    """Frame size keeping the aspect ratio, longest side = size, even numbers."""
    scale = size / max(width, height)
    w = max(2, int(width * scale) // 2 * 2)
    h = max(2, int(height * scale) // 2 * 2)
    return w, h


def convert(src: Path, dest: Path, size: int, fps: float, max_seconds: float) -> dict:
    w, h = cell_size(*probe_size(src), size)
    cols, rows = SHEET // w, SHEET // h
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["ffmpeg", "-loglevel", "error", "-y", "-i", str(src), "-t", str(max_seconds), "-an",
             "-vf", f"fps={fps},scale={w}:{h}", str(Path(tmp) / "%05d.png")],
            check=True,
        )
        frames = len(list(Path(tmp).glob("*.png")))
        subprocess.run(
            ["ffmpeg", "-loglevel", "error", "-y", "-framerate", str(fps), "-i", str(Path(tmp) / "%05d.png"),
             "-vf", f"tile={cols}x{rows},pad={SHEET}:{SHEET}", "-pix_fmt", "bgr24",
             "-start_number", "1", str(dest / "%03d.tga")],
            check=True,
        )
    sheets = len(list(dest.glob("*.tga")))
    info = {"name": src.stem, "frames": frames, "fps": fps, "cols": cols, "rows": rows,
            "width": w, "height": h, "size": SHEET, "sheets": sheets, "source": src.name}
    (dest / "meta.json").write_text(json.dumps(info))
    return info


def write_index(videos_root: Path, addon_root: Path) -> list:
    videos = []
    for d in sorted(p for p in videos_root.iterdir() if p.is_dir()):
        meta = d / "meta.json"
        if meta.exists():
            videos.append((d.name, json.loads(meta.read_text())))
    lines = ["-- Generated by CraftWise tools/video_frames.py. Your own videos; not part of CraftWise.",
             "CraftWiseMusicVideos = {"]
    for folder, v in videos:
        path = f"Interface\\\\AddOns\\\\{ADDON}\\\\Videos\\\\{folder}\\\\"
        lines.append(
            f'\t[{lua_string(v["name"])}] = {{ path = "{path}", sheets = {v["sheets"]}, frames = {v["frames"]}, '
            f'fps = {v["fps"]}, cols = {v["cols"]}, rows = {v["rows"]}, width = {v["width"]}, '
            f'height = {v["height"]}, size = {v["size"]} }},'
        )
    lines.append("}")
    (addon_root / "Videos.lua").write_text("\n".join(lines) + "\n")
    write_toc(addon_root)
    return videos


def write_toc(addon_root: Path):
    files = [f for f in ("Songs.lua", "Videos.lua") if (addon_root / f).exists()]
    (addon_root / f"{ADDON}.toc").write_text(
        f"## Interface: {INTERFACE}\n## Title: CraftWise Music\n"
        "## Notes: Your songs and videos for CraftWise's Music tab\n\n" + "\n".join(files) + "\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("addons", type=Path, help="the Interface/AddOns folder")
    ap.add_argument("videos", type=Path, nargs="*", help="video files (mp4, mov, gif, webm...)")
    ap.add_argument("--size", type=int, default=192, help="longest side of a frame in pixels (default 192)")
    ap.add_argument("--fps", type=float, default=10, help="frames per second (default 10)")
    ap.add_argument("--max-seconds", type=float, default=30, help="cut longer videos (default 30)")
    args = ap.parse_args()
    if args.videos and not shutil.which("ffmpeg"):
        print("ffmpeg not found (macOS: brew install ffmpeg)", file=sys.stderr)
        return 1
    addon_root = args.addons / ADDON
    videos_root = addon_root / "Videos"
    videos_root.mkdir(parents=True, exist_ok=True)
    for src in args.videos:
        info = convert(src, videos_root / folder_name(src), args.size, args.fps, args.max_seconds)
        secs = info["frames"] / info["fps"]
        mb = sum(f.stat().st_size for f in (videos_root / folder_name(src)).glob("*.tga")) / 1e6
        print(f"{src.name}: {info['frames']} frames ({secs:.1f}s at {info['fps']:g} fps), "
              f"{info['width']}x{info['height']}, {info['sheets']} sheets, {mb:.1f} MB")
    for _, v in write_index(videos_root, addon_root):
        print(f"  {v['name']}: {v['frames']} frames")
    print("Restart the game to load new videos.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
